version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=app_loja_games
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    
volumes:
  pgdata:
    driver: local
